spring.application.name=busanit501-EC2

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 1. URL ??: ??? RDS ????? ??? ??????.
# (??: ?? ?? ?? /webdb ? ??? ?????? ?????. ??? ??? DB??? ?? ?????)
spring.datasource.url=jdbc:mariadb://localhost:3306/wedb?serverTimezone=Asia/Seoul&useSSL=false

# 2. ?? ?? ??: ??? RDS ???? ????? ?????.
spring.datasource.username=busanit501
spring.datasource.password=busanit501!!

# //for test (?????? ??? ? ?? - ??)
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2

# JPA ? ?????? ?? (??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# ?? ??
logging.level.org.springframework=info
# 3. ???? ??: org.zerock ??? '?? ????? ?? ????'?? ? ??? ???! (?: com.busanit501.board)
logging.level.com.busanit501=debug
logging.level.org.springframework.security=trace
